version: "3.8"
services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    links:
      - backend
  backend:
    build: ./backend
    env_file:
      - backend/.env
    ports:
      - 8000:8000
    links:
      - database
  database:
    image: postgres:latest
    env_file:
      - backend/.env
    ports:
      - 5432:5432
