version: "3.8"
services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
  backend:
    build: ./backend
    ports:
      - 8000:8000
  database:
    image: library/postgres
    ports:
      - 8001:5432
networks:
  default:
    external:
      name: notes_network